/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    fontSize: {
      "3xs": ["6px",  { lineHeight: "8px" }],
      "2xs": ["7px",  { lineHeight: "10px" }],
      xxs:   ["8px",  { lineHeight: "12px" }],
      xs:    ["9px",  { lineHeight: "12px" }],
      sm:    ["10px", { lineHeight: "14px" }],
      base:  ["11px", { lineHeight: "16px" }],
      md:    ["12px", { lineHeight: "17px" }],
      lg:    ["13px", { lineHeight: "18px" }],
      xl:    ["14px", { lineHeight: "20px" }],
      "2xl": ["15px", { lineHeight: "20px" }],
    },
    extend: {
      colors: {
        dt: {
          bg0: "var(--bg-0)",
          bg1: "var(--bg-1)",
          bg2: "var(--bg-2)",
          bg3: "var(--bg-3)",
          bg4: "var(--bg-4)",
          border: "var(--border)",
          "border-active": "var(--border-active)",
          text0: "var(--text-0)",
          text1: "var(--text-1)",
          text2: "var(--text-2)",
          accent: "var(--accent)",
          "accent-dim": "var(--accent-dim)",
          green: "var(--green)",
          "green-dim": "var(--green-dim)",
          yellow: "var(--yellow)",
          "yellow-dim": "var(--yellow-dim)",
          red: "var(--red)",
          "red-dim": "var(--red-dim)",
          cyan: "var(--cyan)",
          "cyan-dim": "var(--cyan-dim)",
          orange: "var(--orange)",
          "orange-dim": "var(--orange-dim)",
          purple: "var(--purple)",
          "purple-dim": "var(--purple-dim)",
          pink: "var(--pink)",
          "pink-dim": "var(--pink-dim)",
          teal: "var(--teal)",
          "teal-dim": "var(--teal-dim)",
          rose: "var(--rose)",
          "rose-dim": "var(--rose-dim)",
          sky: "var(--sky)",
          "sky-dim": "var(--sky-dim)",
        },
      },
      fontFamily: {
        mono: "var(--font)",
        sans: "var(--font-sans)",
      },
      spacing: {
        "0.75": "2px",
        "1.25": "4px",
        "1.75": "6px",
        "3.75": "14px",
        "4.5":  "18px",
        "7.5":  "28px",
        "13":   "52px",
        "30":   "112px",
        "45":   "168px",
        "50":   "192px",
        "75":   "288px",
      },
      borderRadius: {
        "dt-xs": "0.125rem",
        "dt-sm": "0.1875rem",
        "dt-md": "0.3125rem",
        dt: "0.4375rem",
      },
      keyframes: {
        spin: {
          to: { transform: "rotate(360deg)" },
        },
        "pulse-opacity": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.3" },
        },
        "dash-offset": {
          to: { strokeDashoffset: "-8" },
        },
      },
      animation: {
        spin: "spin .8s linear infinite",
        "pulse-opacity": "pulse-opacity 1.2s ease-in-out infinite",
        "dash-offset": "dash-offset 1s linear infinite",
      },
    },
  },
  plugins: [],
};
