/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    fontSize: {
      "3xs": ["6px",  { lineHeight: "8px" }],
      "2xs": ["7px",  { lineHeight: "10px" }],
      xxs:   ["8px",  { lineHeight: "12px" }],
      xs:    ["9px",  { lineHeight: "12px" }],
      sm:    ["10px", { lineHeight: "14px" }],
      base:  ["11px", { lineHeight: "16px" }],
      md:    ["12px", { lineHeight: "17px" }],
      lg:    ["13px", { lineHeight: "18px" }],
      xl:    ["14px", { lineHeight: "20px" }],
      "2xl": ["15px", { lineHeight: "20px" }],
    },
    extend: {
      colors: {
        dt: {
          // Canonical (Phase 2.5)
          bg: "var(--bg)",
          "bg-s": "var(--bg-s)",
          "bg-e": "var(--bg-e)",
          "bg-h": "var(--bg-h)",
          "bg-sel": "var(--bg-sel)",
          bd: "var(--bd)",
          "bd-s": "var(--bd-s)",
          "bd-faint": "var(--bd-faint)",
          t1: "var(--t1)",
          t2: "var(--t2)",
          t3: "var(--t3)",
          t4: "var(--t4)",
          acc: "var(--acc)",
          "acc-h": "var(--acc-h)",
          "acc-bg": "var(--acc-bg)",
          "acc-glow": "var(--acc-glow)",
          grn: "var(--grn)",
          "grn-bg": "var(--grn-bg)",
          amb: "var(--amb)",
          "amb-bg": "var(--amb-bg)",
          "red-bg": "var(--red-bg)",
          pur: "var(--pur)",
          "pur-bg": "var(--pur-bg)",
          // Category palette (preserves agent role colors)
          "cat-cyan": "var(--cat-cyan)",
          "cat-cyan-bg": "var(--cat-cyan-bg)",
          "cat-purple": "var(--cat-purple)",
          "cat-purple-bg": "var(--cat-purple-bg)",
          "cat-orange": "var(--cat-orange)",
          "cat-orange-bg": "var(--cat-orange-bg)",
          "cat-pink": "var(--cat-pink)",
          "cat-pink-bg": "var(--cat-pink-bg)",
          "cat-rose": "var(--cat-rose)",
          "cat-rose-bg": "var(--cat-rose-bg)",
          // ── Legacy aliases (kept for Tailwind class compat — see Phase 2.5 doc) ──
          bg0: "var(--bg)",
          bg1: "var(--bg-s)",
          bg2: "var(--bg-e)",
          bg3: "var(--bg-h)",
          bg4: "var(--bg-4)",
          border: "var(--bd)",
          "border-active": "var(--bd-s)",
          text0: "var(--t1)",
          text1: "var(--t2)",
          text2: "var(--t3)",
          accent: "var(--acc)",
          "accent-dim": "var(--acc-bg)",
          "accent-hover": "var(--acc-h)",
          "accent-glow": "var(--acc-glow)",
          "border-subtle": "var(--bd-faint)",
          green: "var(--grn)",
          "green-dim": "var(--grn-bg)",
          yellow: "var(--amb)",
          "yellow-dim": "var(--amb-bg)",
          red: "var(--red)",
          "red-dim": "var(--red-bg)",
          cyan: "var(--cat-cyan)",
          "cyan-dim": "var(--cat-cyan-bg)",
          orange: "var(--cat-orange)",
          "orange-dim": "var(--cat-orange-bg)",
          purple: "var(--cat-purple)",
          "purple-dim": "var(--cat-purple-bg)",
          pink: "var(--cat-pink)",
          "pink-dim": "var(--cat-pink-bg)",
          teal: "var(--teal)",
          "teal-dim": "var(--teal-bg)",
          rose: "var(--cat-rose)",
          "rose-dim": "var(--cat-rose-bg)",
          sky: "var(--sky)",
          "sky-dim": "var(--sky-bg)",
        },
      },
      fontFamily: {
        mono: "var(--font)",
        sans: "var(--font-sans)",
      },
      spacing: {
        "0.75": "2px",
        "1.25": "4px",
        "1.75": "6px",
        "3.75": "14px",
        "4.5":  "18px",
        "7.5":  "28px",
        "13":   "52px",
        "30":   "112px",
        "45":   "168px",
        "50":   "192px",
        "75":   "288px",
      },
      boxShadow: {
        'dt-sm': 'var(--shadow-sm)',
        'dt-md': 'var(--shadow-md)',
        'dt-lg': 'var(--shadow-lg)',
        'dt-glow': 'var(--shadow-glow)',
        'dt-focus': 'var(--focus-ring)',
      },
      transitionTimingFunction: {
        'dt-expo': 'var(--ease-out-expo)',
      },
      transitionDuration: {
        'dt-fast': 'var(--duration-fast)',
        'dt-normal': 'var(--duration-normal)',
        'dt-slow': 'var(--duration-slow)',
      },
      backdropBlur: {
        'dt-sm': '8px',
        'dt-md': '16px',
        'dt-lg': '24px',
      },
      borderRadius: {
        "dt-xs": "0.1875rem",
        "dt-sm": "0.3125rem",
        "dt-md": "0.625rem",
        dt: "0.5rem",
        "dt-lg": "0.875rem",
        "dt-xl": "1rem",
      },
      keyframes: {
        spin: {
          to: { transform: "rotate(360deg)" },
        },
        "pulse-opacity": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.3" },
        },
        "dash-offset": {
          to: { strokeDashoffset: "-8" },
        },
        fadeIn: {
          from: { opacity: "0", transform: "translateY(4px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        slideUp: {
          from: { opacity: "0", transform: "translateY(8px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
      },
      animation: {
        spin: "spin .8s linear infinite",
        "pulse-opacity": "pulse-opacity 1.2s ease-in-out infinite",
        "dash-offset": "dash-offset 1s linear infinite",
        "fade-in": "fadeIn var(--duration-normal) var(--ease-out-expo)",
        "slide-up": "slideUp var(--duration-normal) var(--ease-out-expo)",
        shimmer: "shimmer 1.5s ease-in-out infinite",
      },
    },
  },
  plugins: [],
};
